# Basics

workflow:
  - changed-files:
      - any-glob-to-any-file:
          - '.github/workflows/**'

automation:
  - changed-files:
      - any-glob-to-any-file:
          - '.github/*.yml'
          - '.github/*.yaml'
          - '.github/CODEOWNERS'
          - '.github/PULL_REQUEST_TEMPLATE.md'
          - '.github/ISSUE_TEMPLATE/**'

docs:
  - changed-files:
      - any-glob-to-any-file:
          - 'docs/**'
          - '**/docs/**'
          - 'README.md'
          - '**/README.md'
          - 'CONTRIBUTING.md'
          - '**/CONTRIBUTING.md'
          - 'CODE_OF_CONDUCT.md'
          - '**/CODE_OF_CONDUCT.md'
          - 'SUPPORT.md'
          - '**/SUPPORT.md'
          - '**/*.md'

security:
  - changed-files:
      - any-glob-to-any-file:
          - 'SECURITY.md'
          - '.github/security/**'

cargo:
  - changed-files:
      - any-glob-to-any-file:
          - 'Cargo.toml'
          - 'Cargo.lock'
          - '**/Cargo.toml'
          - '**/Cargo.lock'

release:
  - changed-files:
      - any-glob-to-any-file:
          - 'CHANGELOG.md'
          - '**/CHANGELOG.md'

tooling:
  - changed-files:
      - any-glob-to-any-file:
          - 'scripts/**'
          - '.cargo/**'
          - '**/.cargo/**'
          - '.editorconfig'
          - '.gitattributes'
          - '.taplo.toml'
          - '.rustfmt.toml'
          - '.clippy.toml'
          - 'deny.toml'
          - 'spellcheck.toml'
          - 'spellcheck.dic'
          - 'rust-toolchain'
          - 'rust-toolchain.toml'
          - 'package.json'
          - 'package-lock.json'

# Base Crates

tests:
  - changed-files:
      - any-glob-to-any-file:
          - 'tests/**'
          - '**/tests/**'

benches:
  - changed-files:
      - any-glob-to-any-file:
          - 'benches/**'
          - '**/benches/**'

examples:
  - changed-files:
      - any-glob-to-any-file:
          - 'examples/**'
          - '**/examples/**'

bloats:
  - changed-files:
      - any-glob-to-any-file:
          - 'bloats/**'
          - '**/bloats/**'

fuzz:
  - changed-files:
      - any-glob-to-any-file:
          - 'fuzz/**'
          - '**/fuzz/**'

supply-chain:
  - changed-files:
      - any-glob-to-any-file:
          - 'supply-chain/**'
          - '**/supply-chain/**'

crates:
  - changed-files:
      - any-glob-to-any-file:
          - 'crates/**'

# Custom Crates

crates:demo:
  - changed-files:
      - any-glob-to-any-file:
          - 'crates/demo/**'
