apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: edge
  labels:
    release: {{ .Values.metricsRelease }}
spec:
  namespaceSelector:
    matchNames: [{{ .Values.proxyNamespace }}]
  selector:
    matchLabels:
      app.kubernetes.io/name: envoy
  podMetricsEndpoints:
    - port: metrics
      path: /stats/prometheus
      interval: 30s
{{- if .Values.tls }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: certificates
  labels:
    release: {{ .Values.metricsRelease }}
spec:
  namespaceSelector:
    matchNames: [{{ .Values.certManagerNamespace }}]
  selector:
    matchLabels:
      app.kubernetes.io/name: cert-manager
  endpoints:
    - port: tcp-prometheus-servicemonitor
      interval: 60s
{{- end }}
