import { identity } from "@/brand/identity";
import type { Dial } from "@/std/identity";

type Country = {
    iso: string;
    dial: string;
    ar: string;
    en: string;
};

const countries: readonly Country[] = [
    { iso: "EG", dial: "+20", ar: "مصر", en: "Egypt" },
    { iso: "SA", dial: "+966", ar: "السعودية", en: "Saudi Arabia" },
    { iso: "KW", dial: "+965", ar: "الكويت", en: "Kuwait" },
    { iso: "BH", dial: "+973", ar: "البحرين", en: "Bahrain" },
    { iso: "JO", dial: "+962", ar: "الأردن", en: "Jordan" },
    { iso: "QA", dial: "+974", ar: "قطر", en: "Qatar" },
    { iso: "AE", dial: "+971", ar: "الإمارات", en: "Emirates" },
    { iso: "LB", dial: "+961", ar: "لبنان", en: "Lebanon" },
    { iso: "SY", dial: "+963", ar: "سوريا", en: "Syria" },
    { iso: "IQ", dial: "+964", ar: "العراق", en: "Iraq" },
    { iso: "YE", dial: "+967", ar: "اليمن", en: "Yemen" },
    { iso: "OM", dial: "+968", ar: "عمان", en: "Oman" },
    { iso: "PS", dial: "+970", ar: "فلسطين", en: "Palestine" },
    { iso: "US", dial: "+1", ar: "الولايات المتحدة", en: "United States" },
    { iso: "MV", dial: "+960", ar: "المالديف", en: "Maldives" },
    { iso: "IR", dial: "+98", ar: "إيران", en: "Iran" },
    { iso: "MA", dial: "+212", ar: "المغرب", en: "Morocco" },
    { iso: "DZ", dial: "+213", ar: "الجزائر", en: "Algeria" },
    { iso: "TN", dial: "+216", ar: "تونس", en: "Tunisia" },
    { iso: "LY", dial: "+218", ar: "ليبيا", en: "Libya" },
    { iso: "RU", dial: "+7", ar: "روسيا", en: "Russia" },
    { iso: "ZA", dial: "+27", ar: "جنوب أفريقيا", en: "South Africa" },
    { iso: "GR", dial: "+30", ar: "اليونان", en: "Greece" },
    { iso: "NL", dial: "+31", ar: "هولندا", en: "Netherlands" },
    { iso: "BE", dial: "+32", ar: "بلجيكا", en: "Belgium" },
    { iso: "FR", dial: "+33", ar: "فرنسا", en: "France" },
    { iso: "ES", dial: "+34", ar: "إسبانيا", en: "Spain" },
    { iso: "HU", dial: "+36", ar: "المجر", en: "Hungary" },
    { iso: "IT", dial: "+39", ar: "إيطاليا", en: "Italy" },
    { iso: "RO", dial: "+40", ar: "رومانيا", en: "Romania" },
    { iso: "CH", dial: "+41", ar: "سويسرا", en: "Switzerland" },
    { iso: "AT", dial: "+43", ar: "النمسا", en: "Austria" },
    { iso: "GB", dial: "+44", ar: "المملكة المتحدة", en: "United Kingdom" },
    { iso: "DK", dial: "+45", ar: "الدنمارك", en: "Denmark" },
    { iso: "SE", dial: "+46", ar: "السويد", en: "Sweden" },
    { iso: "NO", dial: "+47", ar: "النرويج", en: "Norway" },
    { iso: "PL", dial: "+48", ar: "بولندا", en: "Poland" },
    { iso: "DE", dial: "+49", ar: "ألمانيا", en: "Germany" },
    { iso: "PE", dial: "+51", ar: "بيرو", en: "Peru" },
    { iso: "MX", dial: "+52", ar: "المكسيك", en: "Mexico" },
    { iso: "CU", dial: "+53", ar: "كوبا", en: "Cuba" },
    { iso: "AR", dial: "+54", ar: "الأرجنتين", en: "Argentina" },
    { iso: "BR", dial: "+55", ar: "البرازيل", en: "Brazil" },
    { iso: "CL", dial: "+56", ar: "شيلي", en: "Chile" },
    { iso: "CO", dial: "+57", ar: "كولومبيا", en: "Colombia" },
    { iso: "VE", dial: "+58", ar: "فنزويلا", en: "Venezuela" },
    { iso: "MY", dial: "+60", ar: "ماليزيا", en: "Malaysia" },
    { iso: "AU", dial: "+61", ar: "أستراليا", en: "Australia" },
    { iso: "ID", dial: "+62", ar: "إندونيسيا", en: "Indonesia" },
    { iso: "PH", dial: "+63", ar: "الفلبين", en: "Philippines" },
    { iso: "NZ", dial: "+64", ar: "نيوزيلندا", en: "New Zealand" },
    { iso: "SG", dial: "+65", ar: "سنغافورة", en: "Singapore" },
    { iso: "TH", dial: "+66", ar: "تايلاند", en: "Thailand" },
    { iso: "JP", dial: "+81", ar: "اليابان", en: "Japan" },
    { iso: "KR", dial: "+82", ar: "كوريا الجنوبية", en: "South Korea" },
    { iso: "VN", dial: "+84", ar: "فيتنام", en: "Vietnam" },
    { iso: "CN", dial: "+86", ar: "الصين", en: "China" },
    { iso: "TR", dial: "+90", ar: "تركيا", en: "Turkey" },
    { iso: "IN", dial: "+91", ar: "الهند", en: "India" },
    { iso: "PK", dial: "+92", ar: "باكستان", en: "Pakistan" },
    { iso: "AF", dial: "+93", ar: "أفغانستان", en: "Afghanistan" },
    { iso: "LK", dial: "+94", ar: "سريلانكا", en: "Sri Lanka" },
    { iso: "MM", dial: "+95", ar: "ميانمار", en: "Myanmar" },
    { iso: "GM", dial: "+220", ar: "غامبيا", en: "Gambia" },
    { iso: "SN", dial: "+221", ar: "السنغال", en: "Senegal" },
    { iso: "MR", dial: "+222", ar: "موريتانيا", en: "Mauritania" },
    { iso: "ML", dial: "+223", ar: "مالي", en: "Mali" },
    { iso: "GN", dial: "+224", ar: "غينيا", en: "Guinea" },
    { iso: "CI", dial: "+225", ar: "ساحل العاج", en: "Ivory Coast" },
    { iso: "BF", dial: "+226", ar: "بوركينا فاسو", en: "Burkina Faso" },
    { iso: "NE", dial: "+227", ar: "النيجر", en: "Niger" },
    { iso: "TG", dial: "+228", ar: "توغو", en: "Togo" },
    { iso: "BJ", dial: "+229", ar: "بنين", en: "Benin" },
    { iso: "MU", dial: "+230", ar: "موريشيوس", en: "Mauritius" },
    { iso: "LR", dial: "+231", ar: "ليبيريا", en: "Liberia" },
    { iso: "SL", dial: "+232", ar: "سيراليون", en: "Sierra Leone" },
    { iso: "GH", dial: "+233", ar: "غانا", en: "Ghana" },
    { iso: "NG", dial: "+234", ar: "نيجيريا", en: "Nigeria" },
    { iso: "TD", dial: "+235", ar: "تشاد", en: "Chad" },
    { iso: "CF", dial: "+236", ar: "جمهورية أفريقيا", en: "African Republic" },
    { iso: "CM", dial: "+237", ar: "الكاميرون", en: "Cameroon" },
    { iso: "CV", dial: "+238", ar: "الرأس الأخضر", en: "Cape Verde" },
    { iso: "ST", dial: "+239", ar: "ساو تومي", en: "São Tomé" },
    { iso: "GQ", dial: "+240", ar: "غينيا الاستوائية", en: "Equatorial Guinea" },
    { iso: "GA", dial: "+241", ar: "الغابون", en: "Gabon" },
    { iso: "CG", dial: "+242", ar: "الكونغو", en: "Congo" },
    { iso: "AO", dial: "+244", ar: "أنغولا", en: "Angola" },
    { iso: "GW", dial: "+245", ar: "غينيا بيساو", en: "Guinea-Bissau" },
    { iso: "SC", dial: "+248", ar: "سيشل", en: "Seychelles" },
    { iso: "SD", dial: "+249", ar: "السودان", en: "Sudan" },
    { iso: "RW", dial: "+250", ar: "رواندا", en: "Rwanda" },
    { iso: "ET", dial: "+251", ar: "إثيوبيا", en: "Ethiopia" },
    { iso: "SO", dial: "+252", ar: "الصومال", en: "Somalia" },
    { iso: "DJ", dial: "+253", ar: "جيبوتي", en: "Djibouti" },
    { iso: "KE", dial: "+254", ar: "كينيا", en: "Kenya" },
    { iso: "TZ", dial: "+255", ar: "تنزانيا", en: "Tanzania" },
    { iso: "UG", dial: "+256", ar: "أوغندا", en: "Uganda" },
    { iso: "BI", dial: "+257", ar: "بوروندي", en: "Burundi" },
    { iso: "MZ", dial: "+258", ar: "موزمبيق", en: "Mozambique" },
    { iso: "ZM", dial: "+260", ar: "زامبيا", en: "Zambia" },
    { iso: "MG", dial: "+261", ar: "مدغشقر", en: "Madagascar" },
    { iso: "RE", dial: "+262", ar: "رينيون", en: "Réunion" },
    { iso: "ZW", dial: "+263", ar: "زيمبابوي", en: "Zimbabwe" },
    { iso: "NA", dial: "+264", ar: "ناميبيا", en: "Namibia" },
    { iso: "MW", dial: "+265", ar: "مالاوي", en: "Malawi" },
    { iso: "LS", dial: "+266", ar: "ليسوتو", en: "Lesotho" },
    { iso: "BW", dial: "+267", ar: "بوتسوانا", en: "Botswana" },
    { iso: "SZ", dial: "+268", ar: "إسواتيني", en: "Eswatini" },
    { iso: "KM", dial: "+269", ar: "جزر القمر", en: "Comoros" },
    { iso: "SH", dial: "+290", ar: "سانت هيلينا", en: "Saint Helena" },
    { iso: "ER", dial: "+291", ar: "إريتريا", en: "Eritrea" },
    { iso: "AW", dial: "+297", ar: "أروبا", en: "Aruba" },
    { iso: "FO", dial: "+298", ar: "جزر فارو", en: "Faroe Islands" },
    { iso: "GL", dial: "+299", ar: "جرينلاند", en: "Greenland" },
    { iso: "GI", dial: "+350", ar: "جبل طارق", en: "Gibraltar" },
    { iso: "PT", dial: "+351", ar: "البرتغال", en: "Portugal" },
    { iso: "LU", dial: "+352", ar: "لوكسمبورغ", en: "Luxembourg" },
    { iso: "IE", dial: "+353", ar: "أيرلندا", en: "Ireland" },
    { iso: "IS", dial: "+354", ar: "أيسلندا", en: "Iceland" },
    { iso: "AL", dial: "+355", ar: "ألبانيا", en: "Albania" },
    { iso: "MT", dial: "+356", ar: "مالطا", en: "Malta" },
    { iso: "CY", dial: "+357", ar: "قبرص", en: "Cyprus" },
    { iso: "FI", dial: "+358", ar: "فنلندا", en: "Finland" },
    { iso: "BG", dial: "+359", ar: "بلغاريا", en: "Bulgaria" },
    { iso: "LT", dial: "+370", ar: "ليتوانيا", en: "Lithuania" },
    { iso: "LV", dial: "+371", ar: "لاتفيا", en: "Latvia" },
    { iso: "EE", dial: "+372", ar: "استونيا", en: "Estonia" },
    { iso: "MD", dial: "+373", ar: "مولدوفا", en: "Moldova" },
    { iso: "AM", dial: "+374", ar: "أرمينيا", en: "Armenia" },
    { iso: "BY", dial: "+375", ar: "بيلاروسيا", en: "Belarus" },
    { iso: "AD", dial: "+376", ar: "أندورا", en: "Andorra" },
    { iso: "MC", dial: "+377", ar: "موناكو", en: "Monaco" },
    { iso: "SM", dial: "+378", ar: "سان مارينو", en: "San Marino" },
    { iso: "VA", dial: "+379", ar: "مدينة الفاتيكان", en: "Vatican City" },
    { iso: "UA", dial: "+380", ar: "أوكرانيا", en: "Ukraine" },
    { iso: "RS", dial: "+381", ar: "صربيا", en: "Serbia" },
    { iso: "ME", dial: "+382", ar: "الجبل الأسود", en: "Montenegro" },
    { iso: "XK", dial: "+383", ar: "كوسوفو", en: "Kosovo" },
    { iso: "HR", dial: "+385", ar: "كرواتيا", en: "Croatia" },
    { iso: "SI", dial: "+386", ar: "سلوفينيا", en: "Slovenia" },
    { iso: "BA", dial: "+387", ar: "البوسنة", en: "Bosnia" },
    { iso: "MK", dial: "+389", ar: "مقدونيا الشمالية", en: "North Macedonia" },
    { iso: "CZ", dial: "+420", ar: "جمهورية التشيك", en: "Czech Republic" },
    { iso: "SK", dial: "+421", ar: "سلوفاكيا", en: "Slovakia" },
    { iso: "LI", dial: "+423", ar: "ليختنشتاين", en: "Liechtenstein" },
    { iso: "FK", dial: "+500", ar: "جزر فوكلاند", en: "Falkland Islands" },
    { iso: "BZ", dial: "+501", ar: "بليز", en: "Belize" },
    { iso: "GT", dial: "+502", ar: "غواتيمالا", en: "Guatemala" },
    { iso: "SV", dial: "+503", ar: "السلفادور", en: "El Salvador" },
    { iso: "HN", dial: "+504", ar: "هندوراس", en: "Honduras" },
    { iso: "NI", dial: "+505", ar: "نيكاراغوا", en: "Nicaragua" },
    { iso: "CR", dial: "+506", ar: "كوستاريكا", en: "Costa Rica" },
    { iso: "PA", dial: "+507", ar: "بنما", en: "Panama" },
    { iso: "PM", dial: "+508", ar: "سان بيير", en: "Saint Pierre" },
    { iso: "HT", dial: "+509", ar: "هايتي", en: "Haiti" },
    { iso: "GP", dial: "+590", ar: "جوادلوب", en: "Guadeloupe" },
    { iso: "BO", dial: "+591", ar: "بوليفيا", en: "Bolivia" },
    { iso: "GY", dial: "+592", ar: "غيانا", en: "Guyana" },
    { iso: "EC", dial: "+593", ar: "الإكوادور", en: "Ecuador" },
    { iso: "GF", dial: "+594", ar: "غويانا الفرنسية", en: "French Guiana" },
    { iso: "PY", dial: "+595", ar: "باراغواي", en: "Paraguay" },
    { iso: "MQ", dial: "+596", ar: "مارتينيك", en: "Martinique" },
    { iso: "SR", dial: "+597", ar: "سورينام", en: "Suriname" },
    { iso: "UY", dial: "+598", ar: "أوروغواي", en: "Uruguay" },
    { iso: "TL", dial: "+670", ar: "تيمور الشرقية", en: "Timor-Leste" },
    { iso: "BN", dial: "+673", ar: "بروناي", en: "Brunei" },
    { iso: "NR", dial: "+674", ar: "ناورو", en: "Nauru" },
    { iso: "TO", dial: "+676", ar: "تونغا", en: "Tonga" },
    { iso: "SB", dial: "+677", ar: "جزر سليمان", en: "Solomon Islands" },
    { iso: "VU", dial: "+678", ar: "فانواتو", en: "Vanuatu" },
    { iso: "FJ", dial: "+679", ar: "فيجي", en: "Fiji" },
    { iso: "PW", dial: "+680", ar: "بالاو", en: "Palau" },
    { iso: "CK", dial: "+682", ar: "جزر كوك", en: "Cook Islands" },
    { iso: "NU", dial: "+683", ar: "نيوي", en: "Niue" },
    { iso: "WS", dial: "+685", ar: "ساموا", en: "Samoa" },
    { iso: "KI", dial: "+686", ar: "كيريباتي", en: "Kiribati" },
    { iso: "NC", dial: "+687", ar: "كاليدونيا الجديدة", en: "New Caledonia" },
    { iso: "TV", dial: "+688", ar: "توفالو", en: "Tuvalu" },
    { iso: "PF", dial: "+689", ar: "بولينيزيا الفرنسية", en: "French Polynesia" },
    { iso: "TK", dial: "+690", ar: "توكلاو", en: "Tokelau" },
    { iso: "FM", dial: "+691", ar: "ميكرونيزيا", en: "Micronesia" },
    { iso: "MH", dial: "+692", ar: "جزر مارشال", en: "Marshall Islands" },
    { iso: "KP", dial: "+850", ar: "كوريا الشمالية", en: "North Korea" },
    { iso: "HK", dial: "+852", ar: "هونغ كونغ", en: "Hong Kong" },
    { iso: "MO", dial: "+853", ar: "ماكاو", en: "Macau" },
    { iso: "KH", dial: "+855", ar: "كمبوديا", en: "Cambodia" },
    { iso: "LA", dial: "+856", ar: "لاوس", en: "Laos" },
    { iso: "BT", dial: "+975", ar: "بوتان", en: "Bhutan" },
    { iso: "MN", dial: "+976", ar: "منغوليا", en: "Mongolia" },
    { iso: "NP", dial: "+977", ar: "نيبال", en: "Nepal" },
    { iso: "TJ", dial: "+992", ar: "طاجيكستان", en: "Tajikistan" },
    { iso: "TM", dial: "+993", ar: "تركمانستان", en: "Turkmenistan" },
    { iso: "AZ", dial: "+994", ar: "أذربيجان", en: "Azerbaijan" },
    { iso: "GE", dial: "+995", ar: "جورجيا", en: "Georgia" },
    { iso: "KG", dial: "+996", ar: "قرغيزستان", en: "Kyrgyzstan" },
    { iso: "KZ", dial: "+997", ar: "كازاخستان", en: "Kazakhstan" },
    { iso: "UZ", dial: "+998", ar: "أوزبكستان", en: "Uzbekistan" },
];

export const homeIso = identity.iso;

const popular = new Set([ identity.iso, "IQ", "EG", "SA", "AE", "KW", "QA", "BH", "JO", "LB", "SY", "TR", "US" ]);

export const dialsFor = ( arabic: boolean ): readonly Dial[] => countries.map(( country ) => ({
    iso: country.iso,
    dial: country.dial,
    label: arabic ? country.ar : country.en,
    popular: popular.has(country.iso),
    terms: [ country.ar, country.en, country.iso, country.dial ],
}));
