export type EmojiGroup = "smileys" | "gestures" | "hearts" | "nature" | "food" | "travel" | "objects" | "symbols";

export type Emoji = {
    char: string;
    tags: string;
};

export const emojiGroups: readonly { key: EmojiGroup; glyph: string }[] = [
    { key: "smileys", glyph: "😀" },
    { key: "gestures", glyph: "👍" },
    { key: "hearts", glyph: "❤️" },
    { key: "nature", glyph: "🌿" },
    { key: "food", glyph: "🍔" },
    { key: "travel", glyph: "✈️" },
    { key: "objects", glyph: "💡" },
    { key: "symbols", glyph: "✅" },
];

export const emojis: Record<EmojiGroup, readonly Emoji[]> = {

    smileys: [
        { char: "😀", tags: "grin smile ضحك ابتسامة" },
        { char: "😃", tags: "smile happy مبسوط" },
        { char: "😄", tags: "happy joy فرح" },
        { char: "😁", tags: "beam grin ابتسامة" },
        { char: "😆", tags: "laugh ضحك" },
        { char: "😅", tags: "sweat laugh ضحك عرق" },
        { char: "🤣", tags: "rofl laugh ضحك بشدة" },
        { char: "😂", tags: "tears joy ضحك دموع" },
        { char: "🙂", tags: "slight smile ابتسامة خفيفة" },
        { char: "🙃", tags: "upside سخرية" },
        { char: "😉", tags: "wink غمزة" },
        { char: "😊", tags: "blush خجل" },
        { char: "😇", tags: "angel halo ملاك" },
        { char: "🥰", tags: "love hearts حب" },
        { char: "😍", tags: "heart eyes عشق" },
        { char: "🤩", tags: "star struck انبهار" },
        { char: "😘", tags: "kiss بوسة" },
        { char: "😗", tags: "kiss قبلة" },
        { char: "😋", tags: "yum لذيذ" },
        { char: "😛", tags: "tongue لسان" },
        { char: "🤗", tags: "hug حضن" },
        { char: "🤭", tags: "shy oops خجل" },
        { char: "🤫", tags: "shush صمت" },
        { char: "🤔", tags: "thinking تفكير" },
        { char: "🫡", tags: "salute تحية" },
        { char: "😐", tags: "neutral عادي" },
        { char: "😴", tags: "sleep نوم" },
        { char: "😌", tags: "relieved ارتياح" },
        { char: "😔", tags: "sad حزن" },
        { char: "😢", tags: "cry بكاء" },
        { char: "😭", tags: "sob بكاء شديد" },
        { char: "😤", tags: "steam غضب" },
        { char: "😡", tags: "angry غاضب" },
        { char: "🥺", tags: "pleading رجاء" },
        { char: "😱", tags: "scream خوف" },
        { char: "😳", tags: "flushed احراج" },
        { char: "🥳", tags: "party احتفال" },
        { char: "😎", tags: "cool نظارة" },
        { char: "🤒", tags: "sick مريض" },
        { char: "🤯", tags: "mind blown انفجار" },
    ],

    gestures: [
        { char: "👍", tags: "thumbs up تمام موافق" },
        { char: "👎", tags: "thumbs down رفض" },
        { char: "👌", tags: "ok تمام" },
        { char: "✌️", tags: "victory نصر" },
        { char: "🤞", tags: "fingers crossed حظ" },
        { char: "🤝", tags: "handshake اتفاق مصافحة" },
        { char: "👏", tags: "clap تصفيق" },
        { char: "🙌", tags: "raise hands فرح" },
        { char: "🙏", tags: "pray thanks شكرا دعاء" },
        { char: "💪", tags: "strong قوة" },
        { char: "👋", tags: "wave hello سلام" },
        { char: "🤙", tags: "call اتصال" },
        { char: "✋", tags: "hand يد" },
        { char: "🖐️", tags: "hand raised يد" },
        { char: "👇", tags: "down تحت" },
        { char: "👆", tags: "up فوق" },
        { char: "👉", tags: "right يمين" },
        { char: "👈", tags: "left يسار" },
        { char: "✍️", tags: "writing كتابة" },
        { char: "🤲", tags: "palms دعاء" },
        { char: "🫶", tags: "heart hands حب" },
        { char: "👊", tags: "fist bump قبضة" },
    ],

    hearts: [
        { char: "❤️", tags: "red heart حب قلب" },
        { char: "🧡", tags: "orange heart قلب برتقالي" },
        { char: "💛", tags: "yellow heart قلب اصفر" },
        { char: "💚", tags: "green heart قلب اخضر" },
        { char: "💙", tags: "blue heart قلب ازرق" },
        { char: "💜", tags: "purple heart قلب بنفسجي" },
        { char: "🖤", tags: "black heart قلب اسود" },
        { char: "🤍", tags: "white heart قلب ابيض" },
        { char: "🤎", tags: "brown heart قلب بني" },
        { char: "💔", tags: "broken heart قلب مكسور" },
        { char: "❣️", tags: "heart exclamation قلب" },
        { char: "💕", tags: "two hearts قلوب" },
        { char: "💞", tags: "revolving hearts قلوب" },
        { char: "💓", tags: "beating heart نبض" },
        { char: "💗", tags: "growing heart حب" },
        { char: "💖", tags: "sparkling heart حب لامع" },
        { char: "💘", tags: "cupid سهم حب" },
        { char: "💝", tags: "heart gift هدية" },
        { char: "💯", tags: "hundred مية بالمية" },
        { char: "💋", tags: "kiss بوسة" },
    ],

    nature: [
        { char: "🌿", tags: "herb نبات" },
        { char: "🍀", tags: "clover حظ" },
        { char: "🌸", tags: "blossom زهرة" },
        { char: "🌺", tags: "hibiscus وردة" },
        { char: "🌹", tags: "rose وردة" },
        { char: "🌻", tags: "sunflower شمس" },
        { char: "🌷", tags: "tulip زهرة" },
        { char: "🌴", tags: "palm نخلة" },
        { char: "🌵", tags: "cactus صبار" },
        { char: "🍁", tags: "maple ورقة" },
        { char: "🌞", tags: "sun شمس" },
        { char: "🌙", tags: "moon قمر" },
        { char: "⭐", tags: "star نجمة" },
        { char: "🌟", tags: "glowing star نجمة" },
        { char: "⚡", tags: "lightning برق" },
        { char: "🔥", tags: "fire نار حماس" },
        { char: "❄️", tags: "snow ثلج" },
        { char: "🌊", tags: "wave موج بحر" },
        { char: "🌈", tags: "rainbow قوس قزح" },
        { char: "☁️", tags: "cloud سحاب" },
        { char: "🌧️", tags: "rain مطر" },
        { char: "🐈", tags: "cat قطة" },
        { char: "🐕", tags: "dog كلب" },
        { char: "🦅", tags: "eagle نسر" },
    ],

    food: [
        { char: "🍔", tags: "burger برجر" },
        { char: "🍕", tags: "pizza بيتزا" },
        { char: "🌮", tags: "taco تاكو" },
        { char: "🍟", tags: "fries بطاطس" },
        { char: "🍗", tags: "chicken دجاج" },
        { char: "🥙", tags: "wrap شاورما" },
        { char: "🍚", tags: "rice رز" },
        { char: "🥗", tags: "salad سلطة" },
        { char: "🍞", tags: "bread خبز" },
        { char: "🧀", tags: "cheese جبنة" },
        { char: "🥚", tags: "egg بيض" },
        { char: "🍎", tags: "apple تفاح" },
        { char: "🍌", tags: "banana موز" },
        { char: "🍇", tags: "grapes عنب" },
        { char: "🍉", tags: "watermelon بطيخ" },
        { char: "🍓", tags: "strawberry فراولة" },
        { char: "🌰", tags: "nut مكسرات" },
        { char: "🍰", tags: "cake كيك" },
        { char: "🍫", tags: "chocolate شوكولاتة" },
        { char: "🍦", tags: "ice cream ايس كريم" },
        { char: "☕", tags: "coffee قهوة" },
        { char: "🍵", tags: "tea شاي" },
        { char: "🧃", tags: "juice عصير" },
        { char: "💧", tags: "water ماء" },
    ],

    travel: [
        { char: "✈️", tags: "plane طيارة سفر" },
        { char: "🛫", tags: "departure اقلاع" },
        { char: "🛬", tags: "arrival هبوط" },
        { char: "🧳", tags: "luggage حقيبة شنطة" },
        { char: "🏨", tags: "hotel فندق" },
        { char: "🏝️", tags: "island جزيرة" },
        { char: "🏖️", tags: "beach شاطئ" },
        { char: "⛰️", tags: "mountain جبل" },
        { char: "🕌", tags: "mosque مسجد" },
        { char: "🏛️", tags: "monument اثار" },
        { char: "🗺️", tags: "map خريطة" },
        { char: "🧭", tags: "compass بوصلة" },
        { char: "📍", tags: "pin موقع" },
        { char: "🚗", tags: "car سيارة" },
        { char: "🚕", tags: "taxi تاكسي" },
        { char: "🚌", tags: "bus باص" },
        { char: "🚆", tags: "train قطار" },
        { char: "🚢", tags: "ship سفينة" },
        { char: "⛵", tags: "boat قارب" },
        { char: "🛂", tags: "passport control جوازات" },
        { char: "🎫", tags: "ticket تذكرة" },
        { char: "🗽", tags: "landmark معلم" },
        { char: "🌍", tags: "earth عالم" },
        { char: "🏕️", tags: "camping تخييم" },
    ],

    objects: [
        { char: "💡", tags: "idea فكرة" },
        { char: "📱", tags: "phone موبايل" },
        { char: "💻", tags: "laptop لابتوب" },
        { char: "⌚", tags: "watch ساعة" },
        { char: "📷", tags: "camera كاميرا" },
        { char: "🎧", tags: "headphones سماعة" },
        { char: "🎁", tags: "gift هدية" },
        { char: "🛒", tags: "cart عربة تسوق" },
        { char: "💳", tags: "card بطاقة" },
        { char: "💰", tags: "money فلوس" },
        { char: "🧾", tags: "receipt فاتورة" },
        { char: "🔑", tags: "key مفتاح" },
        { char: "🔒", tags: "lock قفل" },
        { char: "📅", tags: "calendar تقويم" },
        { char: "⏰", tags: "alarm منبه" },
        { char: "📌", tags: "pin تثبيت" },
        { char: "📎", tags: "clip مرفق" },
        { char: "✏️", tags: "pencil قلم" },
        { char: "📖", tags: "book كتاب" },
        { char: "🎓", tags: "graduation تخرج" },
        { char: "🏆", tags: "trophy كأس" },
        { char: "🎉", tags: "party احتفال" },
        { char: "🎂", tags: "birthday عيد ميلاد" },
        { char: "🔔", tags: "bell جرس" },
    ],

    symbols: [
        { char: "✅", tags: "check تمام صح" },
        { char: "❌", tags: "cross خطأ" },
        { char: "⚠️", tags: "warning تحذير" },
        { char: "❓", tags: "question سؤال" },
        { char: "❗", tags: "exclamation تعجب" },
        { char: "✨", tags: "sparkles لمعان" },
        { char: "⭕", tags: "circle دائرة" },
        { char: "🔴", tags: "red circle احمر" },
        { char: "🟢", tags: "green circle اخضر" },
        { char: "🔵", tags: "blue circle ازرق" },
        { char: "🟡", tags: "yellow circle اصفر" },
        { char: "🟠", tags: "orange circle برتقالي" },
        { char: "🔺", tags: "triangle مثلث" },
        { char: "➕", tags: "plus زائد" },
        { char: "➖", tags: "minus ناقص" },
        { char: "♻️", tags: "recycle اعادة" },
        { char: "🆕", tags: "new جديد" },
        { char: "🆓", tags: "free مجاني" },
        { char: "🔝", tags: "top الاعلى" },
        { char: "💤", tags: "sleep نوم" },
    ],

};

export const quickEmojis: readonly string[] = [ "👍", "❤️", "😂", "😮", "😢", "🙏" ];
