__PMA_LIMIT_RULES__

server {
    listen 80;
    server_name __SERVER_IP__;

    client_max_body_size __PMA_MAX_BODY_SIZE__;

    access_log __PMA_ACCESS_LOG__;
    error_log  __PMA_ERROR_LOG__;

    __PMA_AUTH_RULES__

    __PMA_ACCESS_RULES__

    location = /phpmyadmin {
        return 301 /phpmyadmin/;
    }
    location /phpmyadmin/ {
        alias /usr/share/phpmyadmin/;
        index index.php index.html;

        __PMA_LIMIT_USE__
        try_files $uri /phpmyadmin/index.php?$query_string;
    }
    location ~ ^/phpmyadmin/(.+\.php)$ {
        alias /usr/share/phpmyadmin/$1;

        include fastcgi_params;
        fastcgi_pass unix:__PHP_SOCKET__;

        fastcgi_param SCRIPT_FILENAME /usr/share/phpmyadmin/$1;
        fastcgi_read_timeout 300s;
    }
    location ~* ^/phpmyadmin/(.+\.(jpg|jpeg|gif|css|png|js|ico|html|xml|txt|woff2?|svg|map))$ {
        alias /usr/share/phpmyadmin/$1;
        expires 7d;

        access_log off;
        add_header Cache-Control "public, immutable";
    }
    location ~* ^/phpmyadmin/(composer|package(-lock)?|yarn\.lock|pnpm-lock)\.json$ {
        deny all;
    }
    location ~ ^/phpmyadmin/\.(git|svn|ht|env) {
        deny all;
    }
    location ~ /\.ht {
        deny all;
    }
    location / {
        return 404;
    }

    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;

    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
}
