[program:__SESSION_ID___horizon]
process_name=%(program_name)s_%(process_num)02d
command=php __APP_PATH__/artisan horizon

autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data

numprocs=1
redirect_stderr=true
stdout_logfile=__APP_PATH__/storage/logs/horizon.log
stopwaitsecs=3600
