import type { Call } from "../core/wire.ts";

const file = new File(["x"], "a.png", { type: "image/png" });

export const calls: Call[] = [
    ["auth", "login", { email: "a@b.co", password: "p" }],
    ["auth", "register", { name: "Ab", email: "a@b.co", phone: "0123456789", password: "p", password_confirmation: "p" }],
    ["auth", "verify", { challenge_token: "t", otp: "1234" }],
    ["auth", "resend", { challenge_token: "t" }],
    ["auth", "recovery", { phone: "0123456789" }],
    ["auth", "reset", { token: "t", password: "p", password_confirmation: "p" }],
    ["auth", "confirmEmail", { token: "t" }],
    ["auth", "providers", {}],
    ["auth", "socialRedirect", { provider: "google", callback: "https://x.co/cb" }],
    ["auth", "socialExchange", { code: "c" }],
    ["account", "read", {}],
    ["account", "image", { image: file }],
    ["account", "removeImage", {}],
    ["account", "identity", {}],
    ["account", "identityOptions", {}],
    ["account", "submitIdentity", { type: "passport", geo_id: 1, number: "N1", front_image: file }],
    ["account", "preferences", {}],
    ["account", "settings", { language: "ar", currency: "SAR", theme: "dark", notify_prefs: { orders: { enabled: true, channels: { email: false } } } }],
    ["account", "name", { name: "Ali" }],
    ["account", "email", { email: "a@b.co" }],
    ["account", "phone", { phone: "0123456789" }],
    ["account", "password", { password: "p", password_confirmation: "p" }],
    ["account", "location", { address: "x" }],
    ["account", "confirm", { field: "email", code: "1" }],
    ["account", "sendCode", { field: "phone" }],
    ["account", "logout", {}],
    ["account", "logoutAll", {}],
    ["account", "deactivate", { password: "p" }],
    ["account", "delete", { confirm_code: "1" }],
    ["account", "loyalty", {}],
    ["account", "rewards", {}],
    ["account", "socials", {}],
    ["account", "linkSocial", { provider: "google", callback: "https://x.co/cb" }],
    ["account", "unlinkSocial", { provider: "google" }],
    ["sessions", "list", { page: 2 }],
    ["sessions", "revoke", { sessionId: 3 }],
    ["sessions", "revokeOthers", {}],
    ["documents", "read", { documentKey: "about", limit: 5 }],
    ["articles", "list", { page: 1, limit: 5, query: "q", sort: "newest" }],
    ["articles", "view", { articleId: 4 }],
    ["articles", "comments", { articleId: 4, page: 2 }],
    ["articles", "comment", { articleId: 4, content: "hi" }],
    ["articles", "favorite", { articleId: 4 }],
    ["articles", "unfavorite", { articleId: 4 }],
    ["offers", "list", { limit: 3 }],
    ["offers", "view", { offerId: 2 }],
    ["campaigns", "list", {}],
    ["campaigns", "view", { campaignId: 2 }],
    ["content", "read", {}],
    ["settings", "read", {}],
    ["seo", "read", { path: "home" }],
    ["sitemap", "list", { kind: "catalogs", page: 2 }],
    ["policy", "read", {}],
    ["products", "list", {
        categoryId: 1, type: "hotel", view: "full", geo: 7, city: 2, country: "sa", minPrice: "10", maxPrice: "99.5", rating: 4,
        checkin: "2026-10-01", checkout: "2026-10-03", startsFrom: "2026-10-01", startsTo: "2026-10-09", adults: 2, children: 1,
        page: 2, limit: 10, query: "x", sort: "lowest_price",
    }],
    ["products", "view", { productId: 9, adults: 2 }],
    ["products", "availability", { productId: 9, from: "2026-10-01", to: "2026-10-31" }],
    ["products", "reviews", { productId: 9, page: 2 }],
    ["products", "recommendations", { productId: 9, limit: 4 }],
    ["products", "favorite", { productId: 9 }],
    ["products", "unfavorite", { productId: "slug-a" }],
    ["categories", "list", { page: 1, ids: [5, 6], fields: ["name", "image"], facets: ["parent"], stats: ["min_views"], view: "tiny" }],
    ["categories", "view", { categoryId: 5 }],
    ["categories", "products", { categoryId: 5, limit: 2 }],
    ["orders", "list", { page: 1 }],
    ["orders", "view", { orderId: 7 }],
    ["orders", "preview", {
        productId: 9, quantity: 2, starts_at: "2026-10-01", adults: 2, coupon_code: "C1",
        applicants: [{ name: "Ab", birth_date: "2000-01-01" }], addons: [{ catalog_id: 3, quantity: 1 }],
    }],
    ["orders", "quote", { orderId: 7 }],
    ["orders", "pay", { orderId: 7, quote_token: "q", gateway_id: 1, idempotency_key: "k1" }],
    ["orders", "refund", { orderId: 7, amount: "5" }],
    ["orders", "review", { orderId: 7, title: "t", content: "c", rating: 5 }],
    ["orders", "update", { orderId: 7, name: "n", notes: "x" }],
    ["orders", "cancel", { orderId: 7, reason: "r" }],
    ["orders", "checkout", { productId: 9, quantity: 1, quote_token: "q", pay_type: "wallet", email: "a@b.co" }],
    ["cart", "list", {}],
    ["cart", "view", { cartId: 2 }],
    ["cart", "checkout", { cartId: 2, quote_token: "q", pay_type: "later", coupon_code: "C" }],
    ["cart", "add", { productId: 9, quantity: 2 }],
    ["cart", "update", { cartId: 2, quantity: 3 }],
    ["cart", "delete", { cartId: 2 }],
    ["cart", "increment", { cartId: 2, quantity: 1 }],
    ["cart", "decrement", { cartId: 2, quantity: 1 }],
    ["gateways", "list", {}],
    ["gateways", "deposit", { gatewayId: 1, amount: "10", currency: "SAR", recipient: { iban: "x" } }],
    ["gateways", "withdraw", { gatewayId: 1, amount: "10", currency: "SAR" }],
    ["wallet", "read", {}],
    ["wallet", "statement", { page: 2 }],
    ["wallet", "recipient", { recipient: "abc" }],
    ["wallet", "transfer", { recipient: "abc", amount: "1" }],
    ["transactions", "list", {}],
    ["transactions", "view", { transactionId: 3 }],
    ["transactions", "cancel", { transactionId: 3 }],
    ["transactions", "refund", { transactionId: 3, confirm_code: "1" }],
    ["tickets", "view", { ticketId: 1 }],
    ["tickets", "create", { title: "Hello", content: "Hello there" }],
    ["tickets", "update", { ticketId: 1, title: "Hello", content: "Hello there" }],
    ["tickets", "delete", { ticketId: 1 }],
    ["tickets", "list", { status: "closed", page: 1 }],
    ["tickets", "reply", { ticketId: 1, content: "x" }],
    ["tickets", "close", { ticketId: 1 }],
    ["tickets", "resolve", { ticketId: 1 }],
    ["tickets", "reopen", { ticketId: 1 }],
    ["tickets", "forOrder", { orderId: 7, title: "Hello", content: "Hello there" }],
    ["broadcast", "authorize", { socket_id: "1.2", channel_name: "private-wallet.1" }],
    ["notifications", "list", { kind: "order", read: false, pinned: true, page: 1 }],
    ["notifications", "stats", {}],
    ["notifications", "read", { notificationId: 1 }],
    ["notifications", "unread", { notificationId: 1 }],
    ["notifications", "pin", { notificationId: 1 }],
    ["notifications", "unpin", { notificationId: 1 }],
    ["notifications", "delete", { notificationId: 1 }],
    ["notifications", "readMany", { ids: [1, 2] }],
    ["favorites", "list", {}],
    ["favorites", "view", { favoriteId: 1 }],
    ["favorites", "delete", { favoriteId: 1 }],
    ["coupons", "list", {}],
    ["coupons", "mine", {}],
    ["coupons", "history", {}],
    ["coupons", "view", { couponId: 1 }],
    ["coupons", "redeem", { couponId: 1 }],
    ["coupons", "validate", { code: "C1", productId: 9, quantity: 2 }],
    ["levels", "list", {}],
    ["levels", "view", { levelId: 1 }],
    ["referrals", "list", {}],
    ["rewards", "list", {}],
    ["rewards", "view", { rewardId: 1 }],
    ["rewards", "history", {}],
    ["chat", "rooms", { page: 1 }],
    ["chat", "room", { roomId: 1 }],
    ["chat", "support", {}],
    ["chat", "contacts", {}],
    ["announcements", "list", {}],
    ["chat", "search", { search: "x" }],
    ["chat", "open", { userId: 5 }],
    ["chat", "forProduct", { productId: 9 }],
    ["chat", "forOrder", { orderId: 7 }],
    ["messages", "list", { roomId: 1, page: 2 }],
    ["messages", "send", { roomId: 1, content: "hi", files: [file] }],
    ["messages", "edit", { roomId: 1, messageId: 2, content: "e" }],
    ["messages", "forward", { roomId: 1, messageId: 2, targetRoomId: 3 }],
    ["messages", "delete", { roomId: 1, messageId: 2 }],
    ["messages", "read", { roomId: 1 }],
    ["messages", "delivered", { roomId: 1 }],
    ["messages", "react", { roomId: 1, messageId: 2, reaction: "👍" }],
    ["messages", "unreact", { roomId: 1, messageId: 2 }],
    ["messages", "star", { roomId: 1, messageId: 2 }],
    ["messages", "unstar", { roomId: 1, messageId: 2 }],
    ["chat", "typing", { roomId: 1 }],
    ["chat", "pin", { roomId: 1 }],
    ["chat", "unpin", { roomId: 1 }],
    ["chat", "mute", { roomId: 1 }],
    ["chat", "unmute", { roomId: 1 }],
    ["chat", "archive", { roomId: 1 }],
    ["chat", "unarchive", { roomId: 1 }],
    ["chat", "block", { roomId: 1 }],
    ["chat", "unblock", { roomId: 1 }],
    ["chat", "delete", { roomId: 1 }],
    ["chat", "report", { roomId: 1, reason: "rr", content: "cc" }],
    ["chat", "presence", {}],
    ["chat", "visibility", { hidden: true }],
    ["supportMessages", "send", { content: "help" }],
    ["supportMessages", "list", { page: 1 }],
    ["announcementMessages", "list", { roomId: 1 }],
    ["announcementMessages", "react", { roomId: 1, messageId: 2, reaction: "👍" }],
    ["observe", "rooms", {}],
    ["observe", "deleteMessage", { roomId: 1, messageId: 2 }],
    ["reviews", "list", { page: 1 }],
    ["reviews", "restore", { reviewId: 5 }],
    ["comments", "reply", { commentId: 3, content: "r" }],
    ["comments", "removeMany", { ids: [1, 2] }],
    ["replies", "update", { replyId: 4, content: "u" }],
    ["reports", "list", {}],
    ["reports", "remove", { reportId: 2 }],
    ["logs", "list", {}],
    ["logs", "view", { logId: 3 }],
    ["plans", "list", {}],
    ["plans", "coupon", { planId: 1, code: "C1" }],
    ["vendors", "suggest", { query: "z" }],
    ["vendors", "reviews", { vendorId: 2, page: 1 }],
    ["geos", "atlas", {}],
    ["geos", "complete", { query: "ri" }],
    ["geos", "children", { geoId: 3, page: 1 }],
    ["countries", "suggest", { query: "sa" }],
    ["countries", "regions", { countryId: 1, limit: 5 }],
    ["countries", "visit", { countryId: 1 }],
    ["regions", "cities", { regionId: 2 }],
    ["cities", "districts", { cityId: 3 }],
    ["districts", "stats", { districtId: 4 }],
    ["pois", "products", { poiId: 5, page: 1 }],
    ["home", "offers", {}],
    ["home", "products", {}],
    ["search", "list", { query: "riyadh", sort: "newest", filters: { type: "hotel" } }],
    ["search", "suggest", { query: "ri" }],
    ["subscriptions", "preview", { plan_id: 2 }],
    ["subscriptions", "autoRenew", { subscriptionId: 1, auto_renew: true }],
    ["tenants", "list", {}],
    ["tenants", "renew", { tenantId: 1 }],
    ["promotions", "list", {}],
    ["promotions", "delete", { promotionId: 1 }],
    ["credentials", "list", {}],
    ["credentials", "reveal", { token: "abc", password: "p" }],
    ["locales", "list", {}],
    ["currencies", "list", {}],
];
