apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql-metrics
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: saasx
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: prometheus-postgres-exporter
    targetRevision: 8.2.0
    helm:
      valuesObject:
        podLabels:
          infrax.io/peer: postgresql
        config:
          datasource:
            host: postgresql
            port: "5432"
            user: infrax
            database: postgres
            passwordSecret:
              name: postgresql-secrets
              key: ROOT_PASSWORD
            sslmode: disable
        serviceMonitor:
          enabled: true
          namespace: monitoring
  destination:
    server: https://kubernetes.default.svc
    namespace: saasx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
