{{- if and .Values.metrics.path .Values.processes.web }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "service.name" . }}
  labels:
    {{- include "service.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "service.name" . }}
      app.kubernetes.io/component: web
  endpoints:
    - port: http
      path: {{ .Values.metrics.path }}
      interval: 30s
{{- end }}
