import { z } from "../../lib/providers/schema.ts";
import { engage, feature, get, many, post, suggestion } from "../core/dsl.ts";
import {
    ack, count, decimal, dict, flag, list, maybeObject, money, page, picture, ref, seoFields, suggest, tallies, text,
    variants,
} from "../core/fields.ts";
import { check } from "./coupons.ts";
import { gateway } from "./gateways.ts";
import { review } from "./reviews.ts";

const price = z.string().regex(/^\d+(?:\.\d{1,6})?$/);
const adults = z.number().int().min(1).max(30);
const children = z.number().int().min(0).max(30);
const place = z.object({
    id: z.number().nullish(),
    name: text,
    slug: text,
    type: text,
    code: text,
    latitude: decimal,
    longitude: decimal,
}).nullish();
export const location = z.object({
    geo_id: z.number().nullish(),
    country_id: z.number().nullish(),
    city_id: z.number().nullish(),
    latitude: decimal,
    longitude: decimal,
    address: text,
    address_2: text,
    zip_code: text,
    geo: place,
    country: place,
    city: place,
}).nullish();
const attachment = z.object({ type: text, path: text, url: text, variants });
const context = z.object({ unit: text, quantity: decimal }).nullish();
export const trait = z.object({
    id: z.number().nullish(),
    kind: text,
    key: text,
    label: text,
    group: text,
    icon: text,
    type: text,
    code: text,
    number: decimal,
    sort: decimal,
    included: flag,
    value: z.union([z.string(), z.number(), z.boolean()]).nullish(),
    value_label: decimal,
});
const traits = z.array(trait).nullish();
const grouped = z.union([z.record(z.string(), traits), z.array(trait)]).nullish();
const policy = z.object({
    id: z.number(),
    key: text,
    type: text,
    group: text,
    title: text,
    description: text,
    refundable: flag,
    refund_dest: text,
    refund_balance: text,
    free_before_hours: count,
    penalty_percent: decimal,
    deposit_percent: decimal,
    until_stage: text,
    schedule: z.unknown().optional(),
    starts_at: text,
    ends_at: text,
    priority: count,
    sort: count,
});
const host = z.object({
    id: z.number(),
    name: text,
    ...picture,
    verified: flag,
    rating: decimal,
    reviews: count,
    catalogs: count,
    member_since: text,
    response_rate: decimal,
    response_time: text,
}).nullish();
const seat = z.object({
    id: z.number(),
    name: text,
    sku: text,
    min_price: money,
    stock: count,
    adults: count,
    children: count,
    fits: flag,
    sold_out: flag,
    features: dict(z.union([z.string(), z.number()]).nullable()),
});
const rate = z.object({
    id: z.number(),
    name: text,
    currency: text,
    amount: money,
    old_amount: money,
    unit: text,
    kind: text,
    band: text,
    tier: text,
    occupancy: count,
    fee_key: text,
    fee_timing: text,
    basis: text,
    fee_rate_percent: decimal,
    refundable: flag,
    min_units: count,
    max_units: count,
    starts_at: text,
    ends_at: text,
    sort: count,
});
const choice = z.union([z.string(), z.number(), z.boolean()]);
const question = z.object({
    id: z.number(),
    key: z.string(),
    scope: text,
    type: text,
    label: text,
    hint: text,
    required: flag,
    options: z.array(z.string()).nullish(),
    depends_on: text,
    depends_value: z.union([choice, z.array(choice)]).nullish(),
    validity: z.unknown().optional(),
    sort: count,
});
const poi = z.object({
    id: z.number(),
    name: text,
    slug: text,
    kind: text,
    description: text,
    ...picture,
    latitude: decimal,
    longitude: decimal,
    geo: place,
});
const deal = z.object({
    id: z.number().nullish(),
    type: text,
    value_type: text,
    rate: decimal,
    discount: money,
    expires_at: text,
});

export const product = z.object({
    ...seoFields,
    id: z.number(),
    name: z.string(),
    type: z.string(),
    subtype: text,
    role: text,
    capabilities: z.array(z.string()).nullish(),
    category: z.object({ id: z.number(), name: text, image: text, icon: text }).nullish(),
    parent: maybeObject(z.object({ id: z.number(), name: text, slug: text, type: text })),
    description: text,
    instructions: text,
    ...picture,
    attachments: z.array(attachment).nullish(),
    currency: text,
    min_price: money,
    sale_price: money,
    total_price: money,
    price_context: context,
    offer: maybeObject(deal),
    prices: z.array(rate).nullish(),
    bands: z.array(rate).nullish(),
    fees: z.array(rate).nullish(),
    rating: decimal,
    aspects: z.record(z.string(), decimal).nullish(),
    reviews: count,
    orders: count,
    ...tallies,
    featured: flag,
    in_favorites: flag,
    in_cart: flag,
    sale_closed: flag,
    stock: count,
    sku: text,
    barcode: text,
    email: text,
    phone: text,
    delivery: text,
    digital: flag,
    capacity: decimal,
    min_quantity: count,
    max_quantity: count,
    duration: decimal,
    duration_unit: text,
    checkin_time: text,
    checkout_time: text,
    adults: count,
    children: count,
    min_stay: count,
    max_stay: count,
    starts_at: text,
    ends_at: text,
    allow_pay_later: flag,
    transport_mode: text,
    features: grouped,
    details: grouped,
    rules: traits,
    questions: z.array(question).nullish(),
    sellables: z.array(seat).nullish(),
    extras: z.array(z.object({ id: z.number(), name: text, price: money })).nullish(),
    pois: z.array(poi).nullish(),
    pois_count: count,
    faqs: z.array(z.object({ group: text, key: text, question: text, answer: text, sort: count })).nullish(),
    policies: z.array(policy).nullish(),
    host,
    vendor: host,
    geo: location,
    origin: location,
    destination: location,
    sort: count,
    created_at: text,
});

const guests = { adults: adults.optional(), children: children.optional() };
const productId = { productId: ref };
const slot = z.object({
    starts_at: z.string(),
    ends_at: z.string(),
    open: z.boolean(),
    units: count,
});
const day = z.object({
    date: z.string(),
    open: flag,
    units: count,
    price: money,
    sale_price: money,
    slots: z.array(slot).optional(),
});
const availability = z.object({
    slotted: z.boolean().optional(),
    appointment_minutes: z.number().optional(),
    currency: text,
    days: z.array(day),
});

const filters = {
    categoryId: "filters[category]",
    vendor: "filters[vendor]",
    attraction: "filters[attraction]",
    type: "filters[type]",
    geo: "filters[geo]",
    city: "filters[city]",
    country: "filters[country]",
    minPrice: "filters[min_price]",
    maxPrice: "filters[max_price]",
    rating: "filters[min_rating]",
    stars: "filters[min_stars]",
    lat: "filters[lat]",
    lng: "filters[lng]",
    distance: "filters[max_distance]",
    checkin: "filters[checkin]",
    checkout: "filters[checkout]",
    startsFrom: "filters[starts_from]",
    startsTo: "filters[starts_to]",
    adults: "filters[adults]",
    children: "filters[children]",
};

const query = {
    ...list,
    categoryId: ref.optional(),
    vendor: ref.optional(),
    attraction: ref.optional(),
    type: z.string().max(80).optional(),
    geo: ref.optional(),
    city: ref.optional(),
    country: ref.optional(),
    minPrice: price.optional(),
    maxPrice: price.optional(),
    rating: z.number().min(0).max(5).optional(),
    stars: z.number().int().min(1).max(5).optional(),
    lat: z.number().min(-90).max(90).optional(),
    lng: z.number().min(-180).max(180).optional(),
    distance: z.number().min(1).max(500).optional(),
    checkin: z.iso.date().optional(),
    checkout: z.iso.date().optional(),
    startsFrom: z.iso.date().optional(),
    startsTo: z.iso.date().optional(),
    ...guests,
};
const slug = { slug: z.string().regex(/^[a-z][a-z0-9-]*$/).max(200), ...guests };
const purchase = z.object({ product, gateways: z.array(gateway) });
const client = { execution: "client" } as const;

export default feature({ touches: ["favorites"] }, {
    list: get("/catalogs", query, many(product), { cache: 30, request: { fields: filters } }),
    suggest: get("/catalogs/suggest", suggest, many(suggestion)),
    view: get("/catalogs/{productId}", { ...productId, ...guests }, product, { cache: 30 }),
    slug: get("/catalogs/slug/{slug}", slug, product, { cache: 30 }),
    availability: get("/catalogs/{productId}/availability", { ...productId, from: z.iso.date(), to: z.iso.date() }, availability),
    reviews: get("/catalogs/{productId}/reviews", { ...list, ...productId }, many(review)),
    recommendations: get("/catalogs/{productId}/similar", { ...list, ...productId, limit: page.limit }, many(product)),
    order: get("/catalogs/{productId}/order", productId, purchase, { response: { fields: { product: "catalog" } } }),
    coupon: get("/catalogs/{productId}/coupon/{code}", { ...productId, code: z.string().min(1).max(150) }, check),
    favorite: post("/catalogs/{productId}/favorite", productId, ack, client),
    unfavorite: post("/catalogs/{productId}/unfavorite", productId, ack, client),
    discart: post("/catalogs/{productId}/discart", productId, ack, client),
    ...engage("/catalogs/{productId}", productId, ["like", "dislike", "visit", "report"]),
});
