<?php

return [
    'commission' => [
        [
            'key' => 'referral',
            'active' => true,
            'json_value' => [
                'name' => 'referral',
                'after' => 'each_order',
                'scope' => 'transaction',
                'type' => 'amount',
                'balance' => 'pending',
                'pending_days' => 30,
                'points' => 0,
                'amount_type' => 'percentage',
                'amount' => 10,
                'max_amount' => 500,
                'min_price' => 0.01,
                'max_price' => 1000,
                'min_level' => 0,
                'max_level' => 6,
                'max_uses' => 100,
                'max_usages' => 1000,
                'cooldown_days' => 0,
            ]
        ],
        [
            'key' => 'order',
            'active' => true,
            'json_value' => [
                'name' => 'order',
                'after' => 'each_order',
                'scope' => 'unit',
                'type' => 'points',
                'balance' => null,
                'pending_days' => 0,
                'points' => 1,
                'amount_type' => 'fixed',
                'amount' => 0,
                'max_amount' => 500,
                'min_price' => 0.01,
                'max_price' => 1000,
                'min_level' => 0,
                'max_level' => 6,
                'max_uses' => 100,
                'max_usages' => 1000,
                'cooldown_days' => 0,
            ]
        ],
        [
            'key' => 'subscription',
            'active' => true,
            'json_value' => [
                'name' => 'subscription',
                'after' => 'each_subscription',
                'scope' => 'transaction',
                'type' => 'amount',
                'balance' => 'buy',
                'pending_days' => 0,
                'points' => 0,
                'amount_type' => 'fixed',
                'amount' => 0.5,
                'max_amount' => 0,
                'min_price' => 0,
                'max_price' => 0,
                'min_level' => 1,
                'max_level' => 6,
                'max_uses' => 100,
                'max_usages' => 1000,
                'cooldown_days' => 0,
            ]
        ],
        [
            'key' => 'register',
            'active' => true,
            'json_value' => [
                'name' => 'register',
                'after' => 'register',
                'scope' => 'transaction',
                'type' => 'coupon',
                'balance' => null,
                'pending_days' => 0,
                'points' => 0,
                'amount_type' => 'fixed',
                'amount' => 0,
                'coupon' => null,
                'coupon_id' => 0,
                'max_amount' => 0,
                'min_price' => 0,
                'max_price' => 0,
                'min_level' => 0,
                'max_level' => 0,
                'max_uses' => 100,
                'max_usages' => 1000,
                'cooldown_days' => 0,
            ]
        ],
    ],
];
