import type { ComponentProps } from "react";
import GlyphView from "@/elements/glyph";
import {
    Airplane, AppleLogo, Archive, Armchair, ArrowBendDoubleUpRight, ArrowBendUpLeft, ArrowClockwise, ArrowLeft, ArrowRight,ArrowSquareOut,
    ArrowsDownUp, Bathtub, Bed, Bell, BellSlash, Buildings, Bus, CalendarBlank, CalendarCheck, CalendarStar, Camera,
    Car, CaretDown, CaretLeft, CaretRight, CaretUp, ChatCircle, ChatsCircle, Check, CheckCircle, Checks, CigaretteSlash, Clock, Cloud,
    Coffee, Coins, Compass, Confetti, CookingPot, CopySimple, CreditCard, Crown, CurrencyCircleDollar, Devices, Door, DotsThree,
    DownloadSimple, EnvelopeSimple, Export, Eye, EyeSlash, FacebookLogo, FileImage, FilePdf, FileText, Fingerprint, Fire, Flag,
    FolderSimple, FrameCorners, Funnel, Garage, Gauge, GearSix, Gift, GithubLogo, Globe, type Icon as Glyph, GoogleLogo, HandCoins,
    Handshake, Headset, Heart, Hourglass, House, HouseLine, IdentificationCard, Images, Info, InstagramLogo, Key, Lifebuoy, Lightning,
    LinkBreak, LinkedinLogo, LinkSimple, List, LockKey, MagnifyingGlass, MapPin, MapPinLine, MapTrifold, Medal, Megaphone, Minus, Moon,
    NavigationArrow, Newspaper, NotePencil, Package, Paperclip, PaperPlaneTilt, PawPrint, PencilSimple, Percent, Phone, Plus, Power,
    Prohibit, PushPin, Question, Receipt, SealCheck, SealPercent, ShieldCheck, ShieldWarning, ShoppingBag, SignIn, SignOut,
    SlidersHorizontal, Smiley, SnapchatLogo, Snowflake, Sparkle, SquaresFour, Stamp, Star, Storefront, SuitcaseRolling, Sun, Tag, Taxi,
    ThumbsDown, ThumbsUp, Ticket, TiktokLogo, Train, Translate, Trash, Truck, UploadSimple, User, UserCircle, UserMinus, UserPlus,UserSound,
    Users, UsersThree, Wallet, Warning, WarningCircle, WashingMachine, WhatsappLogo, WifiHigh, WindowsLogo, X, XLogo,
    YoutubeLogo,
} from "@/lib/providers/icons";

export type IconName = keyof typeof glyphs;

type Props = Omit<ComponentProps<typeof GlyphView>, "glyph" | "mirrored"> & { name: IconName };

const glyphs = {
    airplane: Airplane,
    "arrow-end": ArrowRight,
    "arrow-start": ArrowLeft,
    bed: Bed,
    bell: Bell,
    calendar: CalendarBlank,
    "calendar-star": CalendarStar,
    "caret-down": CaretDown,
    "caret-end": CaretRight,
    "caret-start": CaretLeft,
    chat: ChatCircle,
    check: Check,
    "check-circle": CheckCircle,
    clock: Clock,
    compass: Compass,
    currency: CurrencyCircleDollar,
    dots: DotsThree,
    mail: EnvelopeSimple,
    facebook: FacebookLogo,
    gear: GearSix,
    gift: Gift,
    globe: Globe,
    handshake: Handshake,
    headset: Headset,
    heart: Heart,
    hourglass: Hourglass,
    house: House,
    "house-line": HouseLine,
    info: Info,
    instagram: InstagramLogo,
    lightning: Lightning,
    linkedin: LinkedinLogo,
    list: List,
    search: MagnifyingGlass,
    pin: MapPin,
    map: MapTrifold,
    medal: Medal,
    minus: Minus,
    moon: Moon,
    near: NavigationArrow,
    news: Newspaper,
    phone: Phone,
    plus: Plus,
    question: Question,
    receipt: Receipt,
    refresh: ArrowClockwise,
    shield: ShieldCheck,
    bag: ShoppingBag,
    "sign-in": SignIn,
    "sign-out": SignOut,
    sliders: SlidersHorizontal,
    snapchat: SnapchatLogo,
    sparkle: Sparkle,
    stamp: Stamp,
    star: Star,
    store: Storefront,
    sun: Sun,
    tag: Tag,
    ticket: Ticket,
    tiktok: TiktokLogo,
    train: Train,
    translate: Translate,
    user: User,
    users: Users,
    wallet: Wallet,
    warning: Warning,
    "warning-circle": WarningCircle,
    whatsapp: WhatsappLogo,
    x: X,
    "x-logo": XLogo,
    youtube: YoutubeLogo,
    sort: ArrowsDownUp,
    wifi: WifiHigh,
    luggage: SuitcaseRolling,
    ban: Prohibit,
    family: UsersThree,
    snow: Snowflake,
    seat: Armchair,
    parking: Garage,
    door: Door,
    camera: Camera,
    bus: Bus,
    washer: WashingMachine,
    truck: Truck,
    taxi: Taxi,
    paw: PawPrint,
    kitchen: CookingPot,
    cloud: Cloud,
    car: Car,
    coffee: Coffee,
    package: Package,
    bath: Bathtub,
    seal: SealCheck,
    area: FrameCorners,
    "id-card": IdentificationCard,
    guide: UserSound,
    share: Export,
    images: Images,
    "no-smoking": CigaretteSlash,
    eye: Eye,
    "eye-off": EyeSlash,
    google: GoogleLogo,
    apple: AppleLogo,
    github: GithubLogo,
    microsoft: WindowsLogo,
    link: LinkSimple,
    unlink: LinkBreak,
    power: Power,
    upload: UploadSimple,
    download: DownloadSimple,
    folder: FolderSimple,
    fingerprint: Fingerprint,
    key: Key,
    "file-pdf": FilePdf,
    "file-image": FileImage,
    "shield-warning": ShieldWarning,
    "user-minus": UserMinus,
    smiley: Smiley,
    "push-pin": PushPin,
    archive: Archive,
    "bell-slash": BellSlash,
    paperclip: Paperclip,
    checks: Checks,
    send: PaperPlaneTilt,
    "note-pencil": NotePencil,
    forward: ArrowBendDoubleUpRight,
    "sign-up": UserPlus,
    "thumbs-up": ThumbsUp,
    "thumbs-down": ThumbsDown,
    reply: ArrowBendUpLeft,
    edit: PencilSimple,
    trash: Trash,
    flag: Flag,
    file: FileText,
    copy: CopySimple,
    external: ArrowSquareOut,
    grid: SquaresFour,
    "user-circle": UserCircle,
    inbox: ChatsCircle,
    support: Lifebuoy,
    fire: Fire,
    crown: Crown,
    coins: Coins,
    card: CreditCard,
    lock: LockKey,
    devices: Devices,
    megaphone: Megaphone,
    percent: Percent,
    "calendar-check": CalendarCheck,
    funnel: Funnel,
    "caret-up": CaretUp,
    "pin-line": MapPinLine,
    buildings: Buildings,
    confetti: Confetti,
    deal: SealPercent,
    payout: HandCoins,
    gauge: Gauge,
} satisfies Record<string, Glyph>;
const directional = new Set<string>(["arrow-end", "arrow-start", "caret-end", "caret-start", "reply"]);

export function isIconName ( value: unknown ): value is IconName {

    return typeof value === "string" && Object.hasOwn(glyphs, value);

}
export default function Icon ({ name, ...props }: Props) {

    return <GlyphView glyph={glyphs[name]} mirrored={directional.has(name)} {...props} />;

}
