import type { SiteConfig } from "../../../src/lib/spec/contract.ts";

export default {
    infos: {
        name: "Zainlak",
        tagline: "",
        description: "",
        copyright: "",
        header_notice: "",
        page_title: "",
        page_description: "",
        page_body: "",
    },
    urls: {
        url: null,
        map_url: null,
    },
    logos: {
        logo: "/assets/images/brand/logo.webp",
        logo_dark: null,
        logo_alt: "Zainlak",
        logo_width: 472,
        logo_height: 112,
        icon: "/assets/images/brand/icon.webp",
        apple_icon: "/assets/images/brand/apple-icon.png",
    },
    address: {
        address_line1: "",
        address_line2: "",
        city: "",
        region: "",
        country: "",
        country_code: "",
        postal_code: "",
    },
    contacts: {
        email: null,
        phone: null,
        whatsapp: null,
        hours: [],
        contacts: [],
        socials: [],
    },
    links: {
        header_links: [],
        links: [],
        link_groups: [],
        social_links: [],
    },
    seo: {
        indexable: false,
        follow: null,
        structured_data: true,
        structured_type: null,
        title: null,
        description: null,
        keywords: null,
        canonical: null,
        image: null,
        image_alt: null,
        image_width: null,
        image_height: null,
        locales: null,
        author: null,
        authors: [],
        creator: null,
        publisher: null,
        category: null,
        published_at: null,
        modified_at: null,
        noarchive: null,
        nosnippet: null,
        noimageindex: null,
        notranslate: null,
        max_snippet: null,
        max_video_preview: null,
        max_image_preview: null,
        unavailable_after: null,
        alternates: [],
        og_type: null,
        og_title: null,
        og_description: null,
        og_site_name: null,
        og_locale: null,
        og_images: [],
        twitter_card: null,
        twitter_site: null,
        twitter_creator: null,
        twitter_title: null,
        twitter_description: null,
        twitter_images: [],
        article_section: null,
        article_tags: [],
        verification_google: null,
        verification_bing: null,
        verification_yandex: null,
        breadcrumbs: [],
    },
} satisfies SiteConfig["contents"];
