import type { SiteConfig } from "../../../src/lib/spec/contract.ts";

export default {
    auth: {
        operations: {
            login: true,
            register: true,
            verify: true,
            resend: true,
            recovery: true,
            reset: true,
            confirmEmail: true,
            providers: true,
            socialRedirect: true,
            socialExchange: true,
            checkEmail: true,
            checkPhone: true,
            checkToken: true,
        },
    },
    account: {
        operations: {
            read: true,
            me: true,
            update: true,
            unlock: true,
            logoutOthers: true,
            files: true,
            uploadFiles: true,
            deleteFiles: true,
            registerDevice: true,
            removeDevice: true,
            attachSocial: true,
            image: true,
            removeImage: true,
            identity: true,
            identityOptions: true,
            submitIdentity: true,
            preferences: true,
            settings: true,
            name: true,
            email: true,
            phone: true,
            password: true,
            location: true,
            confirm: true,
            sendCode: true,
            logout: true,
            logoutAll: true,
            deactivate: true,
            delete: true,
            loyalty: true,
            rewards: true,
            socials: true,
            linkSocial: true,
            unlinkSocial: true,
        },
    },
    sessions: {
        operations: {
            list: true,
            revoke: true,
            revokeOthers: true,
            view: true,
            refresh: true,
            revokeCurrent: true,
            revokeMany: true,
        },
    },
    credentials: {
        operations: {
            list: true,
            current: true,
            view: true,
            create: true,
            reset: true,
            reveal: true,
            delete: true,
        },
    },
    documents: {
        operations: {
            read: true,
        },
    },
    locales: {
        operations: {
            list: true,
        },
    },
    currencies: {
        operations: {
            list: true,
        },
    },
    content: {
        operations: {
            read: true,
        },
    },
    settings: {
        operations: {
            read: true,
        },
    },
    seo: {
        operations: {
            read: true,
        },
    },
    sitemap: {
        operations: {
            list: true,
        },
    },
    policy: {
        operations: {
            read: true,
        },
    },
    home: {
        operations: {
            offers: true,
            categories: true,
            products: true,
        },
    },
    search: {
        operations: {
            list: true,
            suggest: true,
        },
    },
    articles: {
        operations: {
            list: true,
            suggest: true,
            view: true,
            like: true,
            dislike: true,
            visit: true,
            report: true,
            comments: true,
            comment: true,
            favorite: true,
            unfavorite: true,
        },
    },
    offers: {
        operations: {
            list: true,
            view: true,
            effective: true,
        },
    },
    campaigns: {
        operations: {
            list: true,
            suggest: true,
            view: true,
        },
    },
    plans: false,
    products: {
        operations: {
            list: true,
            suggest: true,
            view: true,
            slug: true,
            availability: true,
            reviews: true,
            recommendations: true,
            order: true,
            coupon: true,
            favorite: true,
            unfavorite: true,
            discart: true,
            like: true,
            dislike: true,
            visit: true,
            report: true,
        },
    },
    categories: {
        operations: {
            list: true,
            suggest: true,
            view: true,
            like: true,
            dislike: true,
            visit: true,
            favorite: true,
            unfavorite: true,
            report: true,
            reviews: true,
            coupons: true,
            products: true,
        },
    },
    vendors: {
        operations: {
            list: true,
            suggest: true,
            view: true,
            reviews: true,
        },
    },
    geos: {
        operations: {
            list: true,
            suggest: true,
            view: true,
            like: true,
            dislike: true,
            visit: true,
            unvisit: true,
            favorite: true,
            unfavorite: true,
            report: true,
            atlas: true,
            explore: true,
            complete: true,
            stats: true,
            children: true,
            products: true,
            categories: true,
        },
    },
    countries: {
        operations: {
            list: true,
            suggest: true,
            view: true,
            like: true,
            dislike: true,
            unreact: true,
            reaction: true,
            visit: true,
            unvisit: true,
            favorite: true,
            unfavorite: true,
            report: true,
            stats: true,
            products: true,
            reviews: true,
            regions: true,
            cities: true,
        },
    },
    regions: {
        operations: {
            list: true,
            suggest: true,
            view: true,
            like: true,
            dislike: true,
            unreact: true,
            reaction: true,
            visit: true,
            unvisit: true,
            favorite: true,
            unfavorite: true,
            report: true,
            stats: true,
            products: true,
            reviews: true,
            cities: true,
        },
    },
    cities: {
        operations: {
            list: true,
            suggest: true,
            view: true,
            like: true,
            dislike: true,
            unreact: true,
            reaction: true,
            visit: true,
            unvisit: true,
            favorite: true,
            unfavorite: true,
            report: true,
            stats: true,
            products: true,
            reviews: true,
            districts: true,
        },
    },
    districts: {
        operations: {
            list: true,
            suggest: true,
            view: true,
            like: true,
            dislike: true,
            unreact: true,
            reaction: true,
            visit: true,
            unvisit: true,
            favorite: true,
            unfavorite: true,
            report: true,
            stats: true,
            products: true,
            reviews: true,
        },
    },
    pois: {
        operations: {
            list: true,
            suggest: true,
            view: true,
            like: true,
            dislike: true,
            visit: true,
            unvisit: true,
            favorite: true,
            unfavorite: true,
            report: true,
            products: true,
            reviews: true,
        },
    },
    reviews: {
        operations: {
            list: true,
            view: true,
            replies: true,
            update: true,
            reply: true,
            like: true,
            dislike: true,
            unreact: true,
            reaction: true,
            report: true,
            remove: true,
            restore: true,
            removeMany: true,
            restoreMany: true,
        },
    },
    comments: {
        operations: {
            list: true,
            view: true,
            replies: true,
            update: true,
            reply: true,
            like: true,
            dislike: true,
            unreact: true,
            reaction: true,
            report: true,
            remove: true,
            restore: true,
            removeMany: true,
            restoreMany: true,
        },
    },
    replies: {
        operations: {
            view: true,
            replies: true,
            update: true,
            reply: true,
            like: true,
            dislike: true,
            unreact: true,
            reaction: true,
            report: true,
            remove: true,
            restore: true,
            removeMany: true,
            restoreMany: true,
        },
    },
    reports: {
        operations: {
            list: true,
            view: true,
            update: true,
            remove: true,
            restore: true,
            removeMany: true,
            restoreMany: true,
        },
    },
    logs: {
        operations: {
            list: true,
            view: true,
        },
    },
    orders: {
        operations: {
            list: true,
            view: true,
            preview: true,
            quote: true,
            pay: true,
            refund: true,
            review: true,
            update: true,
            cancel: true,
            checkout: true,
            receive: true,
            revise: true,
            return: true,
            amend: true,
            amendments: true,
            acceptAmendment: true,
            declineAmendment: true,
            reviews: true,
            like: true,
            dislike: true,
            unreact: true,
            reaction: true,
            report: true,
            remove: true,
            restore: true,
            removeMany: true,
            restoreMany: true,
        },
    },
    cart: {
        operations: {
            list: true,
            view: true,
            checkout: true,
            add: true,
            update: true,
            delete: true,
            increment: true,
            decrement: true,
            coupon: true,
            clear: true,
            checkoutAll: true,
        },
    },
    gateways: {
        operations: {
            list: true,
            view: true,
            deposit: true,
            withdraw: true,
        },
    },
    wallet: {
        operations: {
            read: true,
            statement: true,
            recipient: true,
            transfer: true,
        },
    },
    transactions: {
        operations: {
            list: true,
            view: true,
            cancel: true,
            refund: true,
            report: true,
            remove: true,
            restore: true,
            removeMany: true,
            restoreMany: true,
        },
    },
    subscriptions: false,
    tenants: false,
    promotions: {
        operations: {
            list: true,
            view: true,
            create: true,
            update: true,
            delete: true,
        },
    },
    tickets: {
        operations: {
            view: true,
            create: true,
            update: true,
            delete: true,
            list: true,
            reply: true,
            close: true,
            resolve: true,
            reopen: true,
            forOrder: true,
            replies: true,
            report: true,
            restore: true,
            removeMany: true,
            restoreMany: true,
        },
    },
    broadcast: {
        operations: {
            authorize: true,
        },
    },
    notifications: {
        operations: {
            list: true,
            stats: true,
            read: true,
            unread: true,
            pin: true,
            unpin: true,
            delete: true,
            view: true,
            restore: true,
            readMany: true,
            unreadMany: true,
            pinMany: true,
            unpinMany: true,
            restoreMany: true,
            deleteMany: true,
        },
    },
    favorites: {
        operations: {
            list: true,
            view: true,
            delete: true,
            deleteMany: true,
        },
    },
    coupons: {
        operations: {
            list: true,
            mine: true,
            history: true,
            view: true,
            redeem: true,
            report: true,
            validate: true,
        },
    },
    levels: {
        operations: {
            list: true,
            view: true,
            benefits: true,
            like: true,
            dislike: true,
            unreact: true,
            reaction: true,
            report: true,
        },
    },
    referrals: {
        operations: {
            list: true,
            view: true,
            report: true,
            remove: true,
            restore: true,
            removeMany: true,
            restoreMany: true,
        },
    },
    rewards: {
        operations: {
            list: true,
            view: true,
            history: true,
        },
    },
    chat: {
        operations: {
            rooms: true,
            room: true,
            support: true,
            inbox: true,
            team: true,
            platform: true,
            contacts: true,
            search: true,
            open: true,
            context: true,
            forProduct: true,
            forOrder: true,
            typing: true,
            pin: true,
            unpin: true,
            mute: true,
            unmute: true,
            archive: true,
            unarchive: true,
            block: true,
            unblock: true,
            delete: true,
            destroy: true,
            report: true,
            presence: true,
            visibility: true,
        },
    },
    messages: {
        operations: {
            list: true,
            view: true,
            send: true,
            edit: true,
            forward: true,
            read: true,
            delivered: true,
            react: true,
            unreact: true,
            star: true,
            unstar: true,
            pin: true,
            unpin: true,
            delete: true,
            restore: true,
            destroy: true,
        },
    },
    supportMessages: {
        operations: {
            list: true,
            view: true,
            send: true,
            edit: true,
            forward: true,
            read: true,
            delivered: true,
            react: true,
            unreact: true,
            star: true,
            unstar: true,
            pin: true,
            unpin: true,
            delete: true,
            restore: true,
            destroy: true,
        },
    },
    announcements: {
        operations: {
            list: true,
            view: true,
            create: true,
            read: true,
        },
    },
    announcementMessages: {
        operations: {
            list: true,
            view: true,
            send: true,
            edit: true,
            forward: true,
            read: true,
            delivered: true,
            react: true,
            unreact: true,
            star: true,
            unstar: true,
            pin: true,
            unpin: true,
            delete: true,
            restore: true,
            destroy: true,
        },
    },
    observe: {
        operations: {
            rooms: true,
            messages: true,
            deleteMessage: true,
            delete: true,
            archive: true,
            unarchive: true,
        },
    },
} satisfies NonNullable<SiteConfig["features"]>;
