import type { SiteConfig } from "../../../src/lib/spec/contract.ts";

export default {
    colors: {
        light: {
            body: "var(--palette-light-body)",
            panel: "var(--palette-light-panel)",
            popup: "var(--palette-light-popup)",
            control: "var(--palette-light-control)",
            menu: "var(--palette-light-menu)",
            track: "var(--palette-light-track)",
            ink: "var(--palette-light-ink)",
            muted: "var(--palette-light-muted)",
            placeholder: "var(--palette-light-placeholder)",
            disabled: "var(--palette-light-disabled)",
            edge: "var(--palette-light-edge)",
            float: "var(--palette-light-float)",
            line: "var(--palette-light-line)",
            strong: "var(--palette-light-strong)",
            field: "var(--palette-light-field)",
            focus: "var(--palette-light-focus)",
            primary: "var(--palette-light-primary)",
            accent: "var(--palette-light-accent)",
            action: "var(--palette-light-action)",
            ember: "var(--palette-light-ember)",
            offer: "var(--palette-light-offer)",
            success: "var(--palette-light-success)",
            warning: "var(--palette-light-warning)",
            danger: "var(--palette-light-danger)",
            info: "var(--palette-light-info)",
        },
        dark: {
            body: "var(--palette-dark-body)",
            panel: "var(--palette-dark-panel)",
            popup: "var(--palette-dark-popup)",
            control: "var(--palette-dark-control)",
            menu: "var(--palette-dark-menu)",
            track: "var(--palette-dark-track)",
            ink: "var(--palette-dark-ink)",
            muted: "var(--palette-dark-muted)",
            placeholder: "var(--palette-dark-placeholder)",
            disabled: "var(--palette-dark-disabled)",
            edge: "var(--palette-dark-edge)",
            float: "var(--palette-dark-float)",
            line: "var(--palette-dark-line)",
            strong: "var(--palette-dark-strong)",
            field: "var(--palette-dark-field)",
            focus: "var(--palette-dark-focus)",
            primary: "var(--palette-dark-primary)",
            accent: "var(--palette-dark-accent)",
            action: "var(--palette-dark-action)",
            ember: "var(--palette-dark-ember)",
            offer: "var(--palette-dark-offer)",
            success: "var(--palette-dark-success)",
            warning: "var(--palette-dark-warning)",
            danger: "var(--palette-dark-danger)",
            info: "var(--palette-dark-info)",
        },
    },
} satisfies SiteConfig["themes"];
