[DEFAULT]
bantime    = __F2B_BANTIME__
findtime   = __F2B_FINDTIME__
maxretry   = __F2B_MAXRETRY__
backend    = systemd
dbpurgeage = 1d
banaction  = ufw
ignoreip   = 127.0.0.1/8 ::1
usedns     = no
destemail  = root@localhost

[sshd]
enabled  = __F2B_SSHD_ENABLED__
port     = ssh
filter   = sshd
logpath  = %(sshd_log)s
maxretry = __F2B_MAXRETRY__

[recidive]
enabled  = __F2B_RECIDIVE_ENABLED__
filter   = recidive
logpath  = /var/log/fail2ban.log
maxretry = __F2B_MAXRETRY__
findtime = __F2B_FINDTIME__
bantime  = __F2B_BANTIME__

[nginx-http-auth]
enabled  = __F2B_NGINX_ENABLED__
port     = http,https
filter   = nginx-http-auth
logpath  = /var/log/nginx/error.log
maxretry = 6

[mysqld-auth]
enabled  = __F2B_MYSQL_ENABLED__
port     = __F2B_MYSQL_PORT__
filter   = mysqld-auth
logpath  = /var/log/mysql/error.log
maxretry = __F2B_MAXRETRY__
