__APP_LIMIT_RULES__

server {
    listen 80;
    server_name __APP_DOMAIN__;
    return 301 https://$host$request_uri;
}
server {
    listen 443 ssl http2;
    server_name __APP_DOMAIN__;

    ssl_certificate     /etc/letsencrypt/live/__APP_DOMAIN__/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/__APP_DOMAIN__/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;

    root __APP_PATH__/public;
    index index.php index.html;

    client_max_body_size __APP_MAX_BODY_SIZE__;

    access_log __APP_ACCESS_LOG__;
    error_log  __APP_ERROR_LOG__;

    __APP_ACCESS_RULES__

    location / {
        __APP_LIMIT_USE__
        try_files $uri $uri/ /index.php?$query_string;
    }
    location = /app {
        return 301 /app/;
    }
    location /app/ {
        proxy_http_version 1.1;

        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_set_header Sec-WebSocket-Extensions "";
        proxy_set_header Sec-WebSocket-Key $http_sec_websocket_key;
        proxy_set_header Sec-WebSocket-Version $http_sec_websocket_version;

        proxy_read_timeout 600s;
        proxy_send_timeout 600s;

        proxy_pass __APP_SOCKET_HOST__;
    }
    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:__PHP_SOCKET__;
        fastcgi_read_timeout 60s;
    }
    location ~* \.(jpg|jpeg|png|gif|svg|webp|ico|css|js|map|woff2?)$ {
        expires 30d;
        access_log off;
        add_header Cache-Control "public, immutable";

        try_files $uri =404;
    }
    location ~* /(composer|package(-lock)?|yarn\.lock|pnpm-lock)\.json$ {
        deny all;
    }
    location ~ ^/bootstrap/ {
        deny all;
    }
    location ~ /\.(git|svn|env) {
        deny all;
    }
    location ~ /\.ht {
        deny all;
    }

    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
    add_header X-Accel-Buffering no;

    gzip on;
    gzip_vary on;
    gzip_min_length 256;

    gzip_types
        text/plain
        text/css
        application/json
        application/javascript
        application/xml
        application/xml+rss
        text/javascript
        image/svg+xml;
}
