{{- if .Values.tlsEnabled }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    {{- with .Values.sslEmail }}
    email: {{ . | quote }}
    {{- end }}
    privateKeySecretRef:
      name: letsencrypt-account
    solvers:
      {{- if .Values.dns01 }}
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-token
              key: token
      {{- else }}
      - http01:
          gatewayHTTPRoute:
            parentRefs:
              - name: gateway
                namespace: {{ .Release.Namespace }}
                group: gateway.networking.k8s.io
                kind: Gateway
      {{- end }}
{{- end }}
