apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: envoy-gateway
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: {{ .Values.project }}
  source:
    repoURL: docker.io/envoyproxy
    chart: gateway-helm
    targetRevision: v{{ .Values.envoyVersion }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.envoyNamespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
